//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public int MaPhieu { get; set; }
        public string MaNV { get; set; }
        public string ThangNam { get; set; }
        public Nullable<double> TongGioLam { get; set; }
        public Nullable<decimal> LuongTheoGio { get; set; }
        public Nullable<decimal> TienThuong { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
        public decimal TongTien { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
