//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BookingDetailID { get; set; }
        public int BookingID { get; set; }
        public string RoomID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> SoNguoi { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
