//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int MaCC { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayCC { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
        public Nullable<int> MaCa { get; set; }
        public string TrangThai { get; set; }
    
        public virtual CaLamViec CaLamViec { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
